web:
  build: .
  ports:
    - "80:8080"
  volumes:
    - .:/code
  environment:
    NODE_ENV: development
  links:
    - mongo

mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017:27017"
